name: ppe-compliance
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit
    - supabase
    - pandas
    - numpy
    - Pillow
    - ultralytics
    - huggingface_hub
    - scipy
    - opencv-python-headless
    - ffmpeg-python
