name: ppe-compliance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - opencv
  - libgl
  - pip:
    - streamlit
    - supabase
    - pandas
    - numpy
    - Pillow
    - ultralytics
    - huggingface_hub
    - scipy
