name: ppe-compliance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - libgl1-mesa-glx
  - pip:
    - streamlit
    - supabase
    - pandas
    - numpy
    - Pillow
    - opencv-python-headless
    - ultralytics[no-extra]
    - huggingface_hub
    - scipy
